# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Số tiền thực tế được giảm trong đơn hàng này', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền được giảm')),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm voucher được áp dụng vào đơn hàng', verbose_name='Thời điểm áp dụng')),
            ],
            options={
                'verbose_name': 'Order - Voucher',
                'verbose_name_plural': 'Order - Voucher',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm user lưu voucher', verbose_name='Thời điểm lưu')),
                ('used_count', models.IntegerField(default=0, help_text='Số lần user đã sử dụng voucher này', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lần đã sử dụng')),
            ],
            options={
                'verbose_name': 'User - Voucher',
                'verbose_name_plural': 'User - Voucher',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi voucher', primary_key=True, serialize=False, verbose_name='Mã voucher')),
                ('code', models.CharField(help_text='Mã voucher duy nhất để người dùng nhập', max_length=50, unique=True, verbose_name='Mã voucher')),
                ('type', models.CharField(choices=[('platform', 'Platform'), ('seller', 'Seller')], help_text='Platform voucher hoặc seller voucher', max_length=10, verbose_name='Loại voucher')),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], help_text='Giảm theo phần trăm hoặc số tiền cố định', max_length=10, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm giá (% hoặc số tiền)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Giá trị giảm')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Số tiền đơn hàng tối thiểu để áp dụng voucher', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Đơn tối thiểu')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền giảm tối đa (dành cho voucher %)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Giảm tối đa')),
                ('start_date', models.DateField(help_text='Ngày bắt đầu có hiệu lực', verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(help_text='Ngày hết hạn voucher', verbose_name='Ngày hết hạn')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Số lượt sử dụng tối đa toàn hệ thống (NULL = không giới hạn)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Giới hạn sử dụng')),
                ('per_user_limit', models.IntegerField(default=1, help_text='Số lượt sử dụng tối đa mỗi user', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Giới hạn mỗi user')),
                ('is_active', models.BooleanField(default=True, help_text='Voucher có đang hoạt động không', verbose_name='Trạng thái')),
                ('is_auto', models.BooleanField(default=False, help_text='True = tự động áp dụng, False = phải nhập mã', verbose_name='Tự động áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ voucher được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Ngày giờ voucher được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Voucher - Danh mục',
                'verbose_name_plural': 'Voucher - Danh mục',
            },
        ),
        migrations.CreateModel(
            name='VoucherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Voucher - Sản phẩm',
                'verbose_name_plural': 'Voucher - Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='VoucherSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Voucher - Seller',
                'verbose_name_plural': 'Voucher - Seller',
            },
        ),
        migrations.CreateModel(
            name='VoucherStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Voucher cho cửa hàng',
                'verbose_name_plural': 'Voucher cho cửa hàng',
            },
        ),
    ]
