# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0002_initial'),
        ('products', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Cửa hàng sở hữu voucher (NULL nếu là platform voucher)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='store.store', verbose_name='Cửa hàng'),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='ordervoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vouchers', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_categories', to='products.category', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_categories', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='voucherproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_products', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='voucherproduct',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_products', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='voucherseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Người bán'),
        ),
        migrations.AddField(
            model_name='voucherseller',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sellers', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='voucherstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_vouchers', to='store.store', verbose_name='Cửa hàng'),
        ),
        migrations.AddField(
            model_name='voucherstore',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_stores', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AlterUniqueTogether(
            name='uservoucher',
            unique_together={('user', 'voucher')},
        ),
        migrations.AlterUniqueTogether(
            name='vouchercategory',
            unique_together={('voucher', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherproduct',
            unique_together={('voucher', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherseller',
            unique_together={('voucher', 'seller')},
        ),
        migrations.AddConstraint(
            model_name='voucherstore',
            constraint=models.UniqueConstraint(fields=('voucher', 'store'), name='unique_voucher_store'),
        ),
    ]
