# Generated by Django 5.1.6 on 2025-11-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã giỏ hàng')),
                ('session_key', models.CharField(blank=True, help_text='Session ID cho guest user', max_length=40, null=True, verbose_name='Session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Thời gian hết hạn cho giỏ hàng guest', null=True, verbose_name='Ngày hết hạn')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã item')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Giá tại thời điểm thêm vào giỏ hàng', max_digits=12, verbose_name='Đơn giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm vào giỏ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong giỏ hàng',
                'verbose_name_plural': 'Sản phẩm trong giỏ hàng',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã wishlist')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm vào wishlist')),
            ],
            options={
                'verbose_name': 'Danh sách yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
                'ordering': ['-created_at'],
            },
        ),
    ]
