# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã ảnh')),
                ('image', models.ImageField(help_text='Ảnh đính kèm trong đánh giá', upload_to='reviews/images/%Y/%m/', verbose_name='Ảnh đánh giá')),
                ('caption', models.CharField(blank=True, help_text='Mô tả ngắn cho ảnh', max_length=200, null=True, verbose_name='Mô tả ảnh')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Ảnh đánh giá',
                'verbose_name_plural': 'Ảnh đánh giá',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã video')),
                ('video', models.FileField(help_text='Video đính kèm trong đánh giá', upload_to='reviews/videos/%Y/%m/', verbose_name='Video đánh giá')),
                ('thumbnail', models.ImageField(blank=True, help_text='Ảnh thumbnail cho video', null=True, upload_to='reviews/video_thumbnails/%Y/%m/', verbose_name='Ảnh thumbnail')),
                ('duration', models.CharField(blank=True, help_text='Thời lượng video (ví dụ: 0:04)', max_length=10, null=True, verbose_name='Thời lượng')),
                ('caption', models.CharField(blank=True, help_text='Mô tả ngắn cho video', max_length=200, null=True, verbose_name='Mô tả video')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Video đánh giá',
                'verbose_name_plural': 'Video đánh giá',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi đánh giá', primary_key=True, serialize=False, verbose_name='Mã đánh giá')),
                ('rating', models.IntegerField(help_text='Xếp hạng tổng thể của đánh giá (1-5 sao)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Xếp hạng tổng thể')),
                ('size_accuracy', models.CharField(blank=True, choices=[('smaller', 'Nhỏ hơn mô tả'), ('accurate', 'Đúng mô tả'), ('larger', 'Lớn hơn mô tả')], help_text='Đánh giá về size so với mô tả', max_length=20, null=True, verbose_name='Độ chính xác size')),
                ('color_accuracy', models.CharField(blank=True, choices=[('smaller', 'Nhỏ hơn mô tả'), ('accurate', 'Đúng mô tả'), ('larger', 'Lớn hơn mô tả')], help_text='Đánh giá về màu sắc so với mô tả', max_length=20, null=True, verbose_name='Độ chính xác màu sắc')),
                ('material_quality', models.CharField(blank=True, choices=[('poor', 'Kém'), ('average', 'Trung bình'), ('good', 'Tốt'), ('excellent', 'Xuất sắc')], help_text='Đánh giá chất lượng chất liệu', max_length=20, null=True, verbose_name='Chất lượng chất liệu')),
                ('comment', models.TextField(blank=True, help_text='Bình luận chi tiết của đánh giá', null=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ đánh giá được tạo', verbose_name='Ngày tạo')),
                ('order_item', models.ForeignKey(help_text='Mục đơn hàng liên kết với đánh giá này', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.orderitem', verbose_name='Mục đơn hàng')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True, help_text='True = hữu ích, False = không hữu ích', verbose_name='Hữu ích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày vote')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Vote review hữu ích',
                'verbose_name_plural': 'Vote review hữu ích',
            },
        ),
    ]
