# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(help_text='Đánh giá chứa ảnh này', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Đánh giá'),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='review',
            field=models.ForeignKey(help_text='Đánh giá chứa video này', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='reviews.review', verbose_name='Đánh giá'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order_item'], name='reviews_rev_order_i_4b0762_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('order_item',), name='unique_review_per_order_item'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpful',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='unique_helpful_vote_per_review'),
        ),
    ]
