# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi vận chuyển', primary_key=True, serialize=False, verbose_name='Mã vận chuyển')),
                ('tracking_code', models.CharField(blank=True, help_text='Mã theo dõi vận chuyển (nếu có)', max_length=100, null=True, verbose_name='Mã theo dõi')),
                ('pick_name', models.CharField(help_text='Tên của người gửi hàng', max_length=100, verbose_name='Tên người gửi')),
                ('pick_address', models.CharField(help_text='Địa chỉ của người gửi hàng', max_length=255, verbose_name='Địa chỉ người gửi')),
                ('pick_province', models.CharField(help_text='Tỉnh nơi người gửi hàng', max_length=50, verbose_name='Tỉnh người gửi')),
                ('pick_ward', models.CharField(help_text='Phường/Xã nơi người gửi hàng', max_length=50, verbose_name='Phường/Xã người gửi')),
                ('pick_tel', models.CharField(help_text='Số điện thoại của người gửi hàng', max_length=20, verbose_name='Số điện thoại người gửi')),
                ('name', models.CharField(help_text='Tên của người nhận hàng', max_length=100, verbose_name='Tên người nhận')),
                ('address', models.CharField(help_text='Địa chỉ của người nhận hàng', max_length=255, verbose_name='Địa chỉ người nhận')),
                ('province', models.CharField(help_text='Tỉnh nơi người nhận hàng', max_length=50, verbose_name='Tỉnh người nhận')),
                ('ward', models.CharField(help_text='Phường/Xã nơi người nhận hàng', max_length=50, verbose_name='Phường/Xã người nhận')),
                ('hamlet', models.CharField(blank=True, help_text='Thôn/Ấp nơi người nhận hàng (nếu có)', max_length=50, null=True, verbose_name='Thôn/Ấp người nhận')),
                ('tel', models.CharField(help_text='Số điện thoại của người nhận hàng', max_length=20, verbose_name='Số điện thoại người nhận')),
                ('is_freeship', models.BooleanField(default=False, help_text='Đánh dấu nếu vận chuyển miễn phí', verbose_name='Miễn phí vận chuyển')),
                ('pick_date', models.DateField(help_text='Ngày lấy hàng từ người gửi', verbose_name='Ngày lấy hàng')),
                ('pick_money', models.DecimalField(decimal_places=2, default=0.0, help_text='Số tiền thu hộ từ người nhận', max_digits=10, verbose_name='Tiền thu hộ')),
                ('note', models.TextField(blank=True, help_text='Ghi chú thêm về vận chuyển', null=True, verbose_name='Ghi chú')),
                ('value', models.DecimalField(decimal_places=2, help_text='Tổng giá trị của hàng hóa vận chuyển', max_digits=10, verbose_name='Giá trị hàng hóa')),
                ('transport', models.CharField(help_text='Phương tiện được sử dụng để vận chuyển', max_length=50, verbose_name='Phương tiện vận chuyển')),
                ('pick_option', models.CharField(choices=[('cod', 'Cash on Delivery'), ('non_cod', 'Non-Cash on Delivery')], default='cod', help_text='Tùy chọn lấy hàng (COD hoặc không COD)', max_length=10, verbose_name='Tùy chọn lấy hàng')),
                ('deliver_option', models.CharField(choices=[('xteam', 'Xteam'), ('standard', 'Standard')], default='standard', help_text='Tùy chọn giao hàng (Xteam hoặc Standard)', max_length=10, verbose_name='Tùy chọn giao hàng')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', help_text='Trạng thái hiện tại của vận chuyển', max_length=10, verbose_name='Trạng thái vận chuyển')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Tổng khối lượng của hàng hóa vận chuyển', max_digits=10, null=True, verbose_name='Tổng khối lượng')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ vận chuyển được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(blank=True, help_text='Ngày giờ vận chuyển được cập nhật', null=True, verbose_name='Ngày cập nhật')),
                ('sub_order', models.OneToOneField(help_text='Đơn hàng con liên kết với vận chuyển này', on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.suborder', verbose_name='Đơn hàng con')),
            ],
            options={
                'verbose_name': 'Vận chuyển',
                'verbose_name_plural': 'Vận chuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('tracking_id', models.AutoField(help_text='ID duy nhất của bản ghi tracking', primary_key=True, serialize=False, verbose_name='ID tracking')),
                ('status', models.CharField(choices=[('created', 'Created'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], help_text='Trạng thái hiện tại trong lộ trình vận chuyển', max_length=50, verbose_name='Trạng thái lộ trình')),
                ('location', models.CharField(help_text='Vị trí hiện tại của đơn hàng', max_length=255, verbose_name='Vị trí hiện tại')),
                ('details', models.TextField(blank=True, help_text='Mô tả cụ thể về trạng thái hiện tại', null=True, verbose_name='Chi tiết trạng thái')),
                ('timestamp', models.DateTimeField(help_text='Thời gian xảy ra sự kiện trong lộ trình', verbose_name='Thời gian sự kiện')),
                ('carrier_status_code', models.CharField(blank=True, help_text='Mã trạng thái gốc từ API nhà vận chuyển', max_length=50, null=True, verbose_name='Mã trạng thái nhà vận chuyển')),
                ('carrier_status_description', models.TextField(blank=True, help_text='Mô tả trạng thái gốc từ nhà vận chuyển', null=True, verbose_name='Mô tả trạng thái nhà vận chuyển')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Tọa độ vĩ độ của vị trí (nếu có)', max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Tọa độ kinh độ của vị trí (nếu có)', max_digits=11, null=True, verbose_name='Kinh độ')),
                ('estimated_delivery', models.DateTimeField(blank=True, help_text='Thời gian giao hàng dự kiến được cập nhật', null=True, verbose_name='Thời gian giao hàng dự kiến')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian bản ghi tracking được tạo trong hệ thống', verbose_name='Thời gian lưu bản ghi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian bản ghi được cập nhật lần cuối', verbose_name='Thời gian cập nhật')),
                ('api_response', models.JSONField(blank=True, help_text='Phản hồi gốc từ API tracking (để debug)', null=True, verbose_name='Raw API Response')),
                ('sync_at', models.DateTimeField(blank=True, help_text='Thời gian đồng bộ dữ liệu từ API', null=True, verbose_name='Thời gian đồng bộ')),
                ('shipment', models.ForeignKey(help_text='Shipment liên kết với tracking này', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='shipments.shipment', verbose_name='Vận chuyển')),
            ],
            options={
                'verbose_name': 'Lịch sử theo dõi vận chuyển',
                'verbose_name_plural': 'Lịch sử theo dõi vận chuyển',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sub_order'], name='shipments_s_sub_ord_2d1fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_code'], name='shipments_s_trackin_f1c65b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['shipment', 'timestamp'], name='shipments_s_shipmen_78bcec_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['status'], name='shipments_s_status_8832bf_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['timestamp'], name='shipments_s_timesta_fce38d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['created_at'], name='shipments_s_created_9da263_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['sync_at'], name='shipments_s_sync_at_19a51e_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmenttracking',
            constraint=models.UniqueConstraint(fields=('shipment', 'timestamp', 'status'), name='unique_shipment_tracking_status'),
        ),
    ]
