# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã mục')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá tại thời điểm đặt hàng')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Số tiền giảm giá')),
            ],
            options={
                'verbose_name': 'Mục đơn hàng',
                'verbose_name_plural': 'Mục đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('sub_order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn hàng con')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền con')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đã gửi hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy'), ('returned', 'Đã trả hàng')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã vận đơn')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi hàng')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn hàng con',
                'verbose_name_plural': 'Đơn hàng con',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đã gửi hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy'), ('returned', 'Đã trả hàng')], default='pending', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Phí vận chuyển')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='address.address', verbose_name='Địa chỉ giao hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
