# Generated by Django 5.1.6 on 2025-11-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên thương hiệu')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quốc gia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thương hiệu',
                'verbose_name_plural': 'Thương hiệu',
            },
        ),
    ]
