# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã cửa hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cửa hàng')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL thân thiện')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ chi tiết')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Khu vực')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='store/avatars/', verbose_name='Ảnh đại diện')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store/covers/', verbose_name='Ảnh bìa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/logos/', verbose_name='Logo')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Điểm đánh giá')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Tổng số đánh giá')),
                ('followers_count', models.IntegerField(default=0, verbose_name='Số người theo dõi')),
                ('products_count', models.IntegerField(default=0, verbose_name='Số sản phẩm')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Tổng đơn hàng đã bán')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng doanh thu')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10, verbose_name='Trạng thái')),
                ('response_time', models.CharField(blank=True, max_length=20, verbose_name='Thời gian phản hồi')),
                ('response_rate', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Tỷ lệ phản hồi')),
                ('cod_enabled', models.BooleanField(default=True, verbose_name='Cho phép COD')),
                ('express_shipping', models.BooleanField(default=True, verbose_name='Giao hàng nhanh')),
                ('standard_shipping', models.BooleanField(default=True, verbose_name='Giao hàng thường')),
                ('free_shipping_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miễn phí ship từ')),
                ('return_policy', models.TextField(blank=True, verbose_name='Chính sách đổi trả')),
                ('shipping_policy', models.TextField(blank=True, verbose_name='Chính sách vận chuyển')),
                ('warranty_policy', models.TextField(blank=True, verbose_name='Chính sách bảo hành')),
                ('currency', models.CharField(default='VND', max_length=5, verbose_name='Đơn vị tiền tệ')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('join_date', models.DateTimeField(verbose_name='Ngày tham gia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/gallery/', verbose_name='Hình ảnh')),
                ('image_type', models.CharField(choices=[('cover', 'Cover'), ('gallery', 'Gallery'), ('logo', 'Logo'), ('banner', 'Banner')], max_length=10, verbose_name='Loại hình ảnh')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Hình ảnh cửa hàng',
                'verbose_name_plural': 'Hình ảnh cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email được mời')),
                ('role', models.CharField(max_length=50, verbose_name='Vai trò được mời')),
                ('invitation_token', models.CharField(max_length=255, unique=True, verbose_name='Token xác thực')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('expires_at', models.DateTimeField(verbose_name='Thời gian hết hạn')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian chấp nhận')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('message', models.TextField(blank=True, verbose_name='Tin nhắn mời')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Lời mời tham gia',
                'verbose_name_plural': 'Lời mời tham gia',
            },
        ),
        migrations.CreateModel(
            name='StorePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100, unique=True, verbose_name='Tên quyền')),
                ('permission_group', models.CharField(blank=True, max_length=50, verbose_name='Nhóm quyền')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Tên hiển thị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả quyền')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Quyền hạn cửa hàng',
                'verbose_name_plural': 'Quyền hạn cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Điểm đánh giá')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề')),
                ('comment', models.TextField(blank=True, verbose_name='Nội dung đánh giá')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='Ảnh đính kèm')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Số lượt hữu ích')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đánh giá đã xác thực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đánh giá cửa hàng',
                'verbose_name_plural': 'Đánh giá cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='Tên vai trò')),
                ('role_display_name', models.CharField(blank=True, max_length=100, verbose_name='Tên hiển thị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả vai trò')),
                ('default_permissions', models.JSONField(blank=True, null=True, verbose_name='Quyền mặc định')),
                ('is_system_role', models.BooleanField(default=True, verbose_name='Vai trò hệ thống')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Vai trò cửa hàng',
                'verbose_name_plural': 'Vai trò cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=10, verbose_name='Vai trò')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('granted_permissions', models.JSONField(blank=True, null=True, verbose_name='Quyền bổ sung được cấp')),
                ('revoked_permissions', models.JSONField(blank=True, null=True, verbose_name='Quyền bị thu hồi')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian được mời')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian tham gia')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Lần đăng nhập cuối')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Thành viên cửa hàng',
                'verbose_name_plural': 'Thành viên cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='store.store', verbose_name='Cửa hàng')),
                ('auto_confirm_orders', models.BooleanField(default=False, verbose_name='Tự động xác nhận đơn')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Thông báo email')),
                ('notification_sms', models.BooleanField(default=False, verbose_name='Thông báo SMS')),
                ('working_hours_start', models.TimeField(blank=True, null=True, verbose_name='Giờ làm việc bắt đầu')),
                ('working_hours_end', models.TimeField(blank=True, null=True, verbose_name='Giờ làm việc kết thúc')),
                ('working_days', models.JSONField(blank=True, null=True, verbose_name='Ngày làm việc')),
                ('vacation_mode', models.BooleanField(default=False, verbose_name='Chế độ nghỉ phép')),
                ('vacation_message', models.TextField(blank=True, verbose_name='Thông báo nghỉ phép')),
                ('auto_reply_message', models.TextField(blank=True, verbose_name='Tin nhắn tự động')),
            ],
            options={
                'verbose_name': 'Cài đặt cửa hàng',
                'verbose_name_plural': 'Cài đặt cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày thống kê')),
                ('views', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('visitors', models.IntegerField(default=0, verbose_name='Khách truy cập')),
                ('orders', models.IntegerField(default=0, verbose_name='Đơn hàng')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Doanh thu')),
                ('new_followers', models.IntegerField(default=0, verbose_name='Người theo dõi mới')),
                ('products_added', models.IntegerField(default=0, verbose_name='Sản phẩm thêm mới')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='store.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Thống kê cửa hàng',
                'verbose_name_plural': 'Thống kê cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Danh mục chính')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='products.category', verbose_name='Danh mục')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='store.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Danh mục cửa hàng',
                'verbose_name_plural': 'Danh mục cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian theo dõi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn theo dõi')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='store.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Người theo dõi',
                'verbose_name_plural': 'Người theo dõi',
            },
        ),
    ]
