# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storefollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stores', to=settings.AUTH_USER_MODEL, verbose_name='Người theo dõi'),
        ),
        migrations.AddField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.store', verbose_name='Cửa hàng'),
        ),
        migrations.AddField(
            model_name='storeinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_store_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi lời mời'),
        ),
        migrations.AddField(
            model_name='storeinvitation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='store.store', verbose_name='Cửa hàng'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_reviews', to='orders.order', verbose_name='Đơn hàng liên quan'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.store', verbose_name='Cửa hàng'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Người mời'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='store.store', verbose_name='Cửa hàng'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddConstraint(
            model_name='storeanalytics',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='unique_store_analytics_date'),
        ),
        migrations.AddConstraint(
            model_name='storecategory',
            constraint=models.UniqueConstraint(fields=('store', 'category'), name='unique_store_category'),
        ),
        migrations.AddConstraint(
            model_name='storefollower',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_follower'),
        ),
        migrations.AddConstraint(
            model_name='storeuser',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_user'),
        ),
    ]
