# Generated by Django 5.1.6 on 2025-11-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressStore',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã địa chỉ')),
                ('province', models.CharField(help_text='Tên tỉnh/thành phố', max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('ward', models.CharField(help_text='Tên xã/phường', max_length=100, verbose_name='Xã/Phường')),
                ('hamlet', models.CharField(blank=True, help_text='Tên thôn/xóm (có thể để trống)', max_length=100, null=True, verbose_name='Thôn/Xóm')),
                ('detail', models.CharField(help_text='Số nhà, ngõ, đường, v.v.', max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, help_text='Đánh dấu là địa chỉ mặc định của cửa hàng', verbose_name='Địa chỉ mặc định')),
                ('store', models.ForeignKey(help_text='Cửa hàng sở hữu địa chỉ này', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Địa chỉ cửa hàng',
                'verbose_name_plural': 'Địa chỉ cửa hàng',
                'ordering': ['-is_default', 'address_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('store',), name='unique_default_address_per_store')],
            },
        ),
    ]
