# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã thuộc tính')),
                ('name', models.CharField(help_text='VD: Size, Color, Material, Style, Storage...', max_length=50, unique=True, verbose_name='Tên thuộc tính')),
                ('type', models.CharField(choices=[('select', 'Lựa chọn từ danh sách'), ('color', 'Màu sắc (có ảnh)'), ('text', 'Nhập text'), ('number', 'Số')], max_length=10, verbose_name='Loại thuộc tính')),
                ('is_required', models.BooleanField(default=True, verbose_name='Bắt buộc')),
                ('has_image', models.BooleanField(default=False, help_text='Thuộc tính này có ảnh riêng không (thường là Color)', verbose_name='Có ảnh riêng')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Thuộc tính sản phẩm',
                'verbose_name_plural': 'Thuộc tính sản phẩm',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã tùy chọn')),
                ('value', models.CharField(help_text='VD: 39, Đen, Da thật, High-top...', max_length=100, verbose_name='Giá trị')),
                ('value_code', models.CharField(blank=True, help_text='VD: #000000 cho màu đen, XL cho size...', max_length=50, null=True, verbose_name='Mã giá trị')),
                ('image', models.ImageField(blank=True, help_text='Upload ảnh cho tùy chọn này (nếu attribute.has_image = True)', null=True, upload_to='products/attributes/%Y/%m/', verbose_name='Ảnh')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Tùy chọn thuộc tính',
                'verbose_name_plural': 'Tùy chọn thuộc tính',
                'ordering': ['attribute__display_order', 'display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi ảnh', primary_key=True, serialize=False, verbose_name='Mã ảnh')),
                ('image', models.ImageField(help_text='Upload ảnh sản phẩm', upload_to='products/gallery/%Y/%m/', verbose_name='Ảnh sản phẩm')),
                ('is_thumbnail', models.BooleanField(default=False, help_text='Đánh dấu ảnh đại diện của sản phẩm (chỉ được 1 ảnh)', verbose_name='Ảnh đại diện')),
                ('alt_text', models.CharField(blank=True, help_text='Mô tả ảnh cho SEO', max_length=200, null=True, verbose_name='Alt text')),
                ('display_order', models.IntegerField(default=0, help_text='Thứ tự hiển thị ảnh (ảnh đại diện luôn đầu tiên)', verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'ordering': ['-is_thumbnail', 'display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã biến thể')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=8, verbose_name='Khối lượng (kg)')),
                ('option_combinations', models.JSONField(help_text='JSON format: {"Size": "39", "Color": "Đen"}', verbose_name='Kết hợp thuộc tính')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã danh mục')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Ảnh thumbnail cho danh mục', null=True, upload_to='categories/thumbnails/', verbose_name='Ảnh đại diện danh mục')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Giá tham khảo, giá thực tế sẽ theo variant', max_digits=12, verbose_name='Giá cơ bản')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thương hiệu')),
                ('model_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã model')),
                ('size_guide_image', models.ImageField(blank=True, help_text='Upload ảnh bảng hướng dẫn chọn size cho sản phẩm', null=True, upload_to='products/size_guides/', verbose_name='Ảnh hướng dẫn chọn size')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('is_hot', models.BooleanField(default=False, help_text='Sản phẩm bán chạy, được quan tâm nhiều', verbose_name='Sản phẩm hot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
                ('collections', models.ManyToManyField(blank=True, related_name='products', through='collection.ProductCollection', to='collection.collection', verbose_name='Bộ sưu tập')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
