# Generated by Django 5.1.6 on 2025-11-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_rating_product_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hot',
        ),
    ]
