# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.CharField(help_text='ID duy nhất cho bộ sưu tập (VD: summer-2024, sport-elite)', max_length=50, primary_key=True, serialize=False, verbose_name='Mã bộ sưu tập')),
                ('name', models.CharField(help_text='VD: Summer Collection 2024, Sport Elite Series', max_length=255, verbose_name='Tên bộ sưu tập')),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về bộ sưu tập', null=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, help_text='Ảnh đại diện cho bộ sưu tập', null=True, upload_to='collections/images/', verbose_name='Ảnh đại diện')),
                ('product_count', models.IntegerField(default=0, help_text='Số lượng sản phẩm trong bộ sưu tập (tự động tính)', verbose_name='Số sản phẩm')),
                ('featured', models.BooleanField(default=False, help_text='Hiển thị trong phần bộ sưu tập nổi bật', verbose_name='Bộ sưu tập nổi bật')),
                ('season', models.CharField(choices=[('spring', 'Mùa xuân'), ('summer', 'Mùa hè'), ('autumn', 'Mùa thu'), ('winter', 'Mùa đông'), ('all_year', 'Thường niên'), ('special', 'Đặc biệt')], default='all_year', help_text='Mùa hoặc thời gian của bộ sưu tập', max_length=20, verbose_name='Mùa')),
                ('season_custom', models.CharField(blank=True, help_text='VD: Hè 2024, Thu Đông 2024 (nếu không dùng choices)', max_length=100, null=True, verbose_name='Mùa tùy chỉnh')),
                ('is_active', models.BooleanField(default=True, help_text='Bộ sưu tập có được hiển thị hay không', verbose_name='Hoạt động')),
                ('display_order', models.IntegerField(default=0, help_text='Số càng nhỏ hiển thị càng trước', verbose_name='Thứ tự hiển thị')),
                ('slug', models.SlugField(blank=True, help_text='URL thân thiện (tự động tạo từ tên)', max_length=255, unique=True, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, help_text='Mô tả SEO', null=True, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bộ sưu tập',
                'verbose_name_plural': 'Bộ sưu tập',
                'ordering': ['display_order', '-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured_in_collection', models.BooleanField(default=False, help_text='Sản phẩm có nổi bật trong bộ sưu tập này không', verbose_name='Nổi bật trong bộ sưu tập')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm vào bộ sưu tập')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='collection.collection', verbose_name='Bộ sưu tập')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong bộ sưu tập',
                'verbose_name_plural': 'Sản phẩm trong bộ sưu tập',
            },
        ),
    ]
