# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterUniqueTogether(
            name='productcollection',
            unique_together={('product', 'collection')},
        ),
    ]
