# Generated by Django 5.1.6 on 2025-11-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(help_text='Mã định danh duy nhất cho thanh toán.', primary_key=True, serialize=False, verbose_name='Mã thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Tổng số tiền của thanh toán.', max_digits=10, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery')], help_text='Phương thức được sử dụng cho thanh toán.', max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Trạng thái hiện tại của thanh toán.', max_length=10, verbose_name='Trạng thái')),
                ('transaction_id', models.CharField(blank=True, help_text='Mã giao dịch được cung cấp bởi cổng thanh toán.', max_length=100, null=True, verbose_name='Mã giao dịch')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Ngày và giờ khi thanh toán được hoàn thành.', null=True, verbose_name='Thời gian thanh toán')),
                ('order', models.OneToOneField(help_text='Đơn hàng liên kết với thanh toán này.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Đơn hàng')),
            ],
        ),
    ]
