# Generated by Django 5.1.6 on 2025-11-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='buyer', help_text='Xác định quyền của người dùng: Buyer, Seller, Admin', max_length=10, verbose_name='Vai trò'),
        ),
    ]
