# Generated by Django 5.1.6 on 2025-11-19 07:28

import SHOEX.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_default_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện của người dùng (lưu tại D:/PBL6/BackEnd/SHOEX/media/user/)', null=True, upload_to="user/avatar/", verbose_name='Ảnh đại diện'),
        ),
    ]
