# Generated by Django 6.0 on 2025-12-23 18:57

import SHOEX.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện của người dùng (lưu tại D:/PBL6/BackEnd/SHOEX/media/user/)', null=True, upload_to=SHOEX.users.models.user_avatar_upload_path, verbose_name='Ảnh đại diện'),
        ),
    ]
